# Puerto en el que escucha el microservicio de pagos adentro del contenedor.
# Docker Compose lo expone como "pagos-service:8082" en la red interna.
server.port=8082
spring.application.name=pagos-service
